apiVersion: kubero.dev/v1alpha1
kind: Pipeline
metadata:
  name: deploy-jwt-coinbase
spec:
  appRef: jwt-coinbase
  stages:
    - name: build
      actions:
        - type: docker-build
          with:
            context: .
            dockerfile: Dockerfile
            image: docker.io/wongt/jwt-coinbase
            tag: "{{ run.id }}"
            registrySecret: dockerhub-cred
    - name: push
      actions:
        - type: docker-push
          with:
            image: docker.io/wongt/jwt-coinbase
            tag: "{{ run.id }}"
            registrySecret: dockerhub-cred
    - name: deploy
      actions:
        - type: kubectl-set-image
          with:
            resource: deployment/jwt-kuberoapp-web
            container: kuberoapp-web
            image: "docker.io/wongt/jwt-coinbase:{{ run.id }}"
        - type: kubectl-rollout-status
          with:
            resource: deployment/jwt-kuberoapp-web
