apiVersion: kubero.dev/v1alpha1
kind: Pipeline
metadata:
  name: deploy-jwt-coinbase
spec:
  appRef: jwt-coinbase
  stages:
    - name: build
      actions:
        - type: docker-build
          with:
            context: .
            dockerfile: Dockerfile
            image: jwt-coinbase               # local tag (no registry)
            tag: "build-{{ run.id }}"         # unique per run
            load: true                        # make image available to the cluster/pod env
    - name: deploy
      actions:
        # Update the app to use the freshly-built image tag
        - type: kubectl-set-image
          with:
            resource: deployment/jwt-kuberoapp-web
            container: kuberoapp-web
            image: "jwt-coinbase:build-{{ run.id }}"
        - type: kubectl-rollout-status
          with:
            resource: deployment/jwt-kuberoapp-web
